# Generated by Django 2.1.15 on 2023-03-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.CharField(max_length=100)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Project', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_list',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=500)),
            ],
        ),
    ]
