# Generated by Django 2.1.15 on 2023-03-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverallApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=500)),
                ('EmployeeId', models.CharField(max_length=100)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('week_start', models.CharField(max_length=500)),
                ('week_end', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
